export const rolesData = [
  {
    id: 1,
    role: "Compliance Manager",
    type: "In-office",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    role: "Backend Engineer (Typescript/Postgres)",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    role: "React native engineer",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    role: "Compliance Manager",
    type: "In-office",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    role: "Backend Engineer (Typescript/Postgres)",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    role: "React native engineer",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
  {
    id: 7,
    role: "Compliance Manager",
    type: "In-office",
    location: "Lagos, Nigeria",
  },
  {
    id: 8,
    role: "Backend Engineer (Typescript/Postgres)",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
  {
    id: 9,
    role: "React native engineer",
    type: "Remote",
    location: "Lagos, Nigeria",
  },
];

export const trainingData = [
  {
    id: 1,
    course: "Basic Computer",
    code: "(SKO1CA)",
    desc: "Increase your prouductivity and Acquire solid computer skills. Including computer appreciation, Using the Internet, Ms office suit, and coral draw.",
    price: "42",
    dur: "8 weeks",
  },
  {
    id: 2,
    course: "Web Design",
    code: "(SKO2WD)",
    desc: "Learn how to create stunning website designs with html, Css and Javascript.",
    price: "120",
    dur: "12 weeks",
  },
  {
    id: 3,
    course: "Web Development",
    code: "(SKO5DF)",
    desc: "Increase your prouductivity and Acquire solid computer skills. Including computer appreciation, Using the Internet, Ms office suit, and coral draw.",
    price: "330",
    dur: "12 weeks",
  },
  {
    id: 4,
    course: "Flutter Dart",
    code: "(SKOFD)",
    desc: "Learn to build beautiful cross platform mobile applications using the Flutter and Dart",
    price: "350",
    dur: "12 weeks",
  },
  {
    id: 5,
    course: "UI/UK Design",
    code: "(SKOUX)",
    desc: "Learn to create websites and mobile applicaton interfaces and kickstart your career as a UI/UX designer",
    price: "300",
    dur: "11 weeks",
  },
  {
    id: 6,
    course: "Android Development",
    code: "(SKOUX)",
    desc: "Learn Android app development from Scratch to Advance. Learn to code in Java while building fun Android projects.",
    price: "320",
    dur: "12 weeks",
  },
  {
    id: 7,
    course: "Game Development",
    code: "(SKO9GD)",
    desc: " Climb the ladder of Game development with Unreal Engine 4.x and Game development & design using Unity Engine.",
    price: "362",
    dur: "15 weeks",
  },
  {
    id: 8,
    course: "Digital Marketing",
    code: "(SK11DM)",
    desc: "Master Digital Marketing: Advertise using the various Social Media Marketing platforms for Marketing including: SEO, Youtube, Email, Facebook Marketing, Analytics and more!",
    price: "172",
    dur: "18 weeks",
  },
  {
    id: 9,
    course: "Branding",
    code: "(SKO5BD)",
    desc: "Learn the worlds most popular language(Javscript) server-side Development library (Node.js). And build fully functional database.",
    price: "172",
    dur: "8 weeks",
  },
  {
    id: 10,
    course: "Animation (3D)",
    code: "(SK10AD5)",
    desc: "Climb the ladder of Game development with Unreal Engine 4.x and Game development & design using Unity Engine.",
    price: "285",
    dur: "8 weeks",
  },
  {
    id: 11,
    course: "Phyton",
    code: "(SK06PT)",
    desc: "Climb the ladder of Game development with Unreal Engine 4.x and Game development & design using Unity Engine.",
    price: "310",
    dur: "12 weeks",
  },
  {
    id: 12,
    course: "Javascript/Nodejs",
    code: "(SKO6JS)",
    desc: "  Learn the worlds most popular language(Javscript) server-side Development library (Node.js). And build fully functional database.",
    price: "300",
    dur: "12 weeks",
  },
];
