import React from "react";
import Head from "next/head";
import {
  CareerSection1,
  CareerSection2,
  CareerSection3,
  CareerSection4,
  ContactMain,
  Footer,
  Header,
} from "../components";

const Career = () => {
  return (
    <div>
      <Head>
        <title>SoftKode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header black />
      <CareerSection1 />
      <CareerSection2 />
      <CareerSection3 />
      <CareerSection4 />
      <Footer />
    </div>
  );
};

export default Career;
