import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import {
  Footer,
  Header,
  Hero,
  Loading,
  Section1,
  Section2,
  Section3,
  Section4,
  Section5,
  Section6,
  Section7,
  Section8,
} from "../components";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [percent, setPercent] = useState(0);
  useEffect(() => {
    if (loading === true) {
      let clock = setInterval(() => {
        setPercent(percent++);
        if (percent > 100) {
          clearInterval(clock);
          setLoading(false);
        }
      }, 50);
    }
  }, []);
  return (
    <div>
      <Head>
        <title>Softkode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <Loading loading={loading} percent={percent} />
      ) : (
        <>
          <Header />
          <Hero />
          <Section1 />
          <Section2 />
          <Section3 />
          <Section4 />
          <Section5 />
          <Section6 />
          <Section7 />
          <Section8 />
          <Footer />
        </>
      )}
    </div>
  );
}
