import React from "react";
import Head from "next/head";
import {
  Footer,
  Header,
  ProjectSection1,
  ProjectSection2,
  ProjectSection3,
} from "../components";

const projects = () => {
  return (
    <div>
      <Head>
        <title>SoftKode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ProjectSection1 />
      <ProjectSection2 />
      <ProjectSection3 />
      <Footer />
    </div>
  );
};

export default projects;
