import React from "react";
import Head from "next/head";
import {
  Footer,
  Header,
  TrainingSection1,
  TrainingSection2,
  TrainingSection3,
} from "../components";

const training = () => {
  return (
    <div>
      <Head>
        <title>SoftKode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <TrainingSection1 />
      <TrainingSection2 />
      <TrainingSection3 />
      <Footer />
    </div>
  );
};

export default training;
