import React from "react";
import Head from "next/head";
import {
  Footer,
  Header,
  MemberMain,
  TrainingSection1,
  TrainingSection2,
  TrainingSection3,
} from "../../components";
import { useRouter } from "next/router";

const Member = () => {
  const router = useRouter();
  const { name } = router.query;
  return (
    <div>
      <Head>
        <title>SoftKode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MemberMain name={name} />
      <Footer />
    </div>
  );
};

export default Member;
